# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tierschutzverein - MeSaHayKoDer - Türkei
email: mesahaykoder@gmail.com
telefon: +9 (0) 538 779 84 79
description: > # Tierschutz - MeSaHayKoDer - Özdere/Türkei


baseurl: /mesahaykoder # the subpath of your site, e.g. /blog
url: "http://www.tierheim-oezdere.de/" # the base hostname & protocol for your site
facebook_username: /1-Euro-für-Özdere-Tierheim-Özdere-183449288408025/?fref=ts
facebook_title: MeSaHayKoDer

# Build settings
markdown: kramdown
