# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tierschutzverein - MeSaHayKoDer - Özdere/Türkei
email: service@mesahaykoder.de
telefon: +9 (0) 538 779 84 79
info_email: mrtnriemer@aol.com
description: > # Tierschutz - MeSaHayKoDer - Özdere/Türkei


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mesahaykoder.de" # the base hostname & protocol for your site
facebook_username: /1-Euro-für-Özdere-Tierheim-Özdere-183449288408025/?fref=ts
facebook_title: MeSaHayKoDer
fb_app_id: 456138037927901

sass:
  style: compressed

# Build settings
markdown: kramdown
collections:
  paten_tiere:
    output: true
    permalink: /patenschaft/gesucht/:title/
  aktuelles:
    output: true
    permalink: /aktuelles/:title/
